/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug  8 2014, 14:49:54                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "math.h"
#include "stdlib.h"
#include "adc.h"

static GRAPH_DATA_Handle  data_tab;
static GRAPH_SCALE_Handle hScaleV;   // Handle of vertical scale
static GRAPH_SCALE_Handle hScaleH;   // Handle of horizontal scale

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x09)
#define ID_GRAPH_0 (GUI_ID_USER + 0x0A)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 320, 240, 0, 0x64, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 0, 0, 310, 215, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/


// USER START (Optionally insert additional static code)
// USER END


/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
	float adcVal;
  switch (pMsg->MsgId) {
      case WM_TIMER:{
          WM_RestartTimer(pMsg->Data.v, 2);
		  adcVal = Get_Adc_Average(ADC_Channel_1, 10)/24;
		  GRAPH_DATA_YT_AddValue(data_tab, (I16)adcVal);
      }break;
	  
  case WM_INIT_DIALOG:
    hItem =WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
    GRAPH_SetBorder(hItem,40, 5, 5, 30);                //设置边框 左顶右下
    GRAPH_SetGridVis(hItem,1);                          //设置网格线可见
    GRAPH_SetGridFixedX(hItem,1);                       //固定x方向的网格
    GRAPH_SetGridDistY(hItem,25);                       //设置Y方向两个网格之间的距离为25
    GRAPH_SetGridDistX(hItem,50);                       //设置X方向两个网格之间的距离为50

    hScaleV =GRAPH_SCALE_Create(30, GUI_TA_RIGHT, GRAPH_SCALE_CF_VERTICAL, 25);//创建和增加垂直范围尺度标签
    GRAPH_SCALE_SetTextColor(hScaleV,GUI_RED);     //设置标签字体颜色
    GRAPH_AttachScale(hItem,hScaleV);    //将标签添加到垂直方向
    hScaleH =GRAPH_SCALE_Create(195, GUI_TA_HCENTER, GRAPH_SCALE_CF_HORIZONTAL, 50);//创建和增加水平范围尺度标签
    GRAPH_SCALE_SetTextColor(hScaleH,GUI_DARKGREEN);    //设置字体颜色
    GRAPH_AttachScale(hItem,hScaleH);      //添加到水平方向
    data_tab = GRAPH_DATA_YT_Create(GUI_GREEN, 500, 0, 0);//创建一个数据曲线,可创建多个曲线
    GRAPH_AttachData(hItem, data_tab);     //为绘图控件添加数据对象

    //
    // Initialization of 'Framewin'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, GUI_FONT_16B_1);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetText(hItem, "GRAPH_TEST");
    FRAMEWIN_SetTextColor(hItem, 0x00000000);
    //
    // Initialization of 'Graph'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
    GRAPH_SetBorder(hItem, 40, 3, 3, 25);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/

WM_HWIN CreateFramewin_GRAPH(void) {
  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  WM_CreateTimer(WM_GetClientWindow(hWin),1, 10, 0); //创建一个软件定时器
  return hWin;
}
void MainTask(void){
    GUI_Init();
   // WM_SetCallback(WM_HBKWIN, &_cbBkWindow_dropdown);
    WM_SetCreateFlags(WM_CF_MEMDEV);

	//设置皮肤
	BUTTON_SetDefaultSkin(BUTTON_SKIN_FLEX);
	CHECKBOX_SetDefaultSkin(CHECKBOX_SKIN_FLEX);
	DROPDOWN_SetDefaultSkin(DROPDOWN_SKIN_FLEX);
	FRAMEWIN_SetDefaultSkin(FRAMEWIN_SKIN_FLEX);
	HEADER_SetDefaultSkin(HEADER_SKIN_FLEX);
	MENU_SetDefaultSkin(MENU_SKIN_FLEX);
	MULTIPAGE_SetDefaultSkin(MULTIPAGE_SKIN_FLEX);
	PROGBAR_SetDefaultSkin(PROGBAR_SKIN_FLEX);
	RADIO_SetDefaultSkin(RADIO_SKIN_FLEX);
	SCROLLBAR_SetDefaultSkin(SCROLLBAR_SKIN_FLEX);
	SLIDER_SetDefaultSkin(SLIDER_SKIN_FLEX);
	SPINBOX_SetDefaultSkin(SPINBOX_SKIN_FLEX);

	CreateFramewin_GRAPH();

	while(1)
    {
        GUI_Exec();
    }
}

/*************************** End of file ****************************/
